services:
  postgresdb:
    image: postgres:15.2
    container_name: postgresdb
    restart: always
    environment:
      POSTGRES_USER: depocheck
      POSTGRES_PASSWORD: depocheck
      POSTGRES_DB: db_depocheck
    ports:
      - "5432:5432"
    user: "depocheck"

  depocheck:
    build: .
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgresdb:5432/db_depocheck
      - SPRING_DATASOURCE_USERNAME=depocheck
      - SPRING_DATASOURCE_PASSWORD=depocheck
    depends_on:
      - postgresdb